backend:
  name: git-gateway
  branch: main # O el nombre de tu rama de GitHub (usualmente main o master)

media_folder: "fotos" # La carpeta donde se van a guardar tus imágenes
public_folder: "fotos"

collections:
  - name: "portfolio"
    label: "Mis Fotos"
    folder: "contenido" # Creá una carpeta llamada 'contenido' al lado de tu index.html
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Título de la foto", name: "title", widget: "string" }
      - { label: "Fecha", name: "date", widget: "datetime" }
      - { label: "Imagen", name: "image", widget: "image" }