backend:
  name: test-repo

media_folder: "images"
public_folder: "/images"

collections:
  - name: "portfolio"
    label: "Portfolio"
    label_singular: "Foto"
    folder: "_data"
    extension: "json"
    format: "json"
    create: true
    slug: "{{slug}}"
    identifier_field: "title"
    summary: "{{title}} - {{date}}"
    fields:
      - { label: "Título", name: "title", widget: "string" }
      - { label: "Descripción", name: "description", widget: "text" }
      - { label: "Fecha", name: "date", widget: "datetime", format: "YYYY-MM-DD" }
      - { label: "Imagen", name: "image", widget: "image", media_library: { config: { max_file_size: 5000000 } } }
      - { label: "Alt Text", name: "alt", widget: "string" }